services:
  db:
    image: mysql:8.0.37
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sairam0704*
      MYSQL_USER: root
      MYSQL_PASSWORD: Sairam0704*
      MYSQL_DATABASE: streamlytics
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://root:Sairam0704*@db/streamlytics"

volumes:
  db_data: